/*
* Generated file
*
* Generated from: yang module name: sfc-monitor-impl yang module local name: sfc-monitor-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri May 06 00:36:36 BRT 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_monitor.impl;
public class SfcMonitorModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_monitor.impl.AbstractSfcMonitorModuleFactory {

}
